version: "3"

services:
  server:
    build: gunicorn
    networks:
      - server
    ports:
      - "8000:8000"
  haproxy:
    build: haproxy
    ports:
      - "8001:8001"
    networks:
      - server
    environment:
      - SERVER_HOSTNAME=server
      - SERVER_PORT=8000
  mitmproxy:
    build: mitmproxy
    ports:
      - "8002:8002"
    networks:
      - server
    environment:
      - SERVER_HOSTNAME=server
      - SERVER_PORT=8000
  squidproxy:
    build: squidproxy
    ports:
      - "8003:8003"
    networks:
      - server
  nginxproxy:
    build: nginxproxy
    ports:
      - "8004:8004"
    networks:
      - server
networks:
  server:
